name: CI-init-script-check

on:
  workflow_dispatch:
  push:

env:
#  DOWNLOAD_DIST: ${{ inputs.download-dist }}
  GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: integ-test-cache-cleanup-${{ github.run_number }}-
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  full-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Download distribution if required
      uses: ./.github/actions/download-dist
    - name: Setup Gradle
      uses: ./
      with:
        cache-read-only: false # For testing, allow writing cache entries on non-default branches
    - name: Build with 3.1
      working-directory: test/jest/resources/cache-cleanup
      run: ./gradlew --no-daemon --build-cache -Dcommons-math3.version=3.1 build

  # Second build will use the cache from the first build, but cleanup should remove unused artifacts
  assemble-build:
    needs: full-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Download distribution if required
      uses: ./.github/actions/download-dist
    - name: Setup Gradle
      uses: ./
      with:
        cache-read-only: false
        gradle-home-cache-cleanup: true

    - name: Report Gradle User Home
      run: du -hc ~/.gradle/caches/modules-2
    - name: Build with 3.1.1
      working-directory: test/jest/resources/cache-cleanup
      run: ./gradlew --no-daemon --build-cache -Dcommons-math3.version=3.1.1 build
    - name: Report Gradle User Home
      run: du -hc ~/.gradle/caches/modules-2

  check-clean-cache:
    needs: assemble-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Download distribution if required
      uses: ./.github/actions/download-dist
    - name: Setup Gradle
      uses: ./
      with:
        cache-read-only: true
    - name: Report Gradle User Home
      run: du -hc ~/.gradle/caches/modules-2
