name: Test cache cleanup

on:
  workflow_dispatch:

env:
#  DOWNLOAD_DIST: ${{ inputs.download-dist }}
  GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: integ-test-cache-cleanup-${{ inputs.cache-key-prefix }}
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  full-build:
    runs-on: ubutuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Download distribution if required
      uses: ./.github/actions/download-dist
    - name: Setup Gradle
      uses: ./
      with:
        cache-read-only: false # For testing, allow writing cache entries on non-default branches
    - name: Full build of groovy-dsl project
      working-directory: .github/workflow-samples/groovy-dsl
      run: ./gradlew build --build-cache

  # Second build will use the cache from the first build, but cleanup should remove unused artifacts
  assemble-build:
    needs: full-build
    runs-on: ubutuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Download distribution if required
      uses: ./.github/actions/download-dist
    - name: Setup Gradle
      uses: ./
      with:
        cache-read-only: false
        gradle-home-cache-cleanup: true
    - name: Assemble groovy-dsl project
      working-directory: .github/workflow-samples/groovy-dsl
      run: ./gradlew assemble --build-cache

  check-clean-cache:
    needs: assemble-build
    runs-on: ubutuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Download distribution if required
      uses: ./.github/actions/download-dist
    - name: Setup Gradle
      uses: ./
      with:
        cache-read-only: true
    - name: Report Gradle User Home
      run: du -hct 1M ~/.gradle/caches/modules-2
